/**
 * Comprehensive list of Nigerian States and their respective Cities / Local Government Areas (LGAs)
 */
export const NIGERIA_STATES: Record<string, string[]> = {
  'Abia': [
    'Aba North',
    'Aba South',
    'Arochukwu',
    'Bende',
    'Ikwuano',
    'Isiala Ngwa North',
    'Isiala Ngwa South',
    'Isuikwuato',
    'Obi Ngwa',
    'Ohafia',
    'Osisioma',
    'Ugwunagbo',
    'Ukwa East',
    'Ukwa West',
    'Umuahia North',
    'Umuahia South',
    'Umu Nneochi',
  ],
  'Abuja (FCT)': [
    'Abuja Central',
    'Garki',
    'Wuse',
    'Maitama',
    'Asokoro',
    'Guzape',
    'Jabi',
    'Utako',
    'Gwarinpa',
    'Life Camp',
    'Kubwa',
    'Lugbe',
    'Airport Road',
    'Lokogoma',
    'Apo',
    'Dawaki',
    'Mpape',
    'Bwari',
    'Kuje',
    'Gwagwalada',
    'Kwali',
    'Abaji',
  ],
  'Adamawa': [
    'Yola North',
    'Yola South',
    'Jimeta',
    'Mubi North',
    'Mubi South',
    'Gombi',
    'Numan',
    'Fufore',
    'Ganye',
    'Guyuk',
    'Hong',
    'Jada',
    'Lamurde',
    'Madagali',
    'Maiha',
    'Michika',
    'Song',
    'Toungo',
  ],
  'Akwa Ibom': [
    'Uyo',
    'Eket',
    'Ikot Ekpene',
    'Oron',
    'Abak',
    'Ikot Abasi',
    'Etinan',
    'Ibiono Ibom',
    'Ibesikpo Asutan',
    'Mkpat Enin',
    'Nsit Ibom',
    'Nsit Ubium',
    'Onna',
    'Ukanafun',
    'Uruan',
  ],
  'Anambra': [
    'Awka North',
    'Awka South',
    'Onitsha North',
    'Onitsha South',
    'Nnewi North',
    'Nnewi South',
    'Aguata',
    'Anaocha',
    'Dunukofia',
    'Ekwusigo',
    'Idemili North',
    'Idemili South',
    'Ihiala',
    'Njikoka',
    'Ogbaru',
    'Oyi',
  ],
  'Bauchi': [
    'Bauchi',
    'Azare',
    'Misau',
    'Jamaare',
    'Katagum',
    'Alkaleri',
    'Dass',
    'Ganjuwa',
    'Ningi',
    'Toro',
    'Warji',
    'Zaki',
  ],
  'Bayelsa': [
    'Yenagoa',
    'Brass',
    'Ekeremor',
    'Kolokuma/Opokuma',
    'Nembe',
    'Ogbia',
    'Sagbama',
    'Southern Ijaw',
  ],
  'Benue': [
    'Makurdi',
    'Gboko',
    'Otukpo',
    'Katsina-Ala',
    'Vandeikya',
    'Buruku',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Konshisha',
    'Kwande',
    'Oju',
    'Okpokwu',
    'Ukum',
    'Ushongo',
  ],
  'Borno': [
    'Maiduguri',
    'Jere',
    'Bama',
    'Biu',
    'Damboa',
    'Gwoza',
    'Hawul',
    'Kaga',
    'Konduga',
    'Kukawa',
    'Munguno',
  ],
  'Cross River': [
    'Calabar Municipal',
    'Calabar South',
    'Akamkpa',
    'Akpabuyo',
    'Bakassi',
    'Bekwarra',
    'Biase',
    'Boki',
    'Ikom',
    'Obubra',
    'Obudu',
    'Odukpani',
    'Ogoja',
    'Yakurr',
    'Yala',
  ],
  'Delta': [
    'Asaba',
    'Warri',
    'Ughelli North',
    'Ughelli South',
    'Sapele',
    'Agbor (Ika South)',
    'Ika North East',
    'Effurun (Uvwie)',
    'Okpe',
    'Oshimili North',
    'Oshimili South',
    'Aniocha North',
    'Aniocha South',
    'Ethiope East',
    'Ethiope West',
    'Isoko North',
    'Isoko South',
    'Ndokwa East',
    'Ndokwa West',
    'Udu',
  ],
  'Ebonyi': [
    'Abakaliki',
    'Afikpo North',
    'Afikpo South',
    'Ebonyi',
    'Ezza North',
    'Ezza South',
    'Ikwo',
    'Ishielu',
    'Ivo',
    'Izzi',
    'Ohaozara',
    'Ohaukwu',
    'Onicha',
  ],
  'Edo': [
    'Benin City (Oredo)',
    'Ikpoba Okha',
    'Egor',
    'Uselu',
    'Ugbowo',
    'GRA Benin',
    'Ekpoma (Esan West)',
    'Uromi (Esan North East)',
    'Esan Central',
    'Esan South East',
    'Auchi (Etsako West)',
    'Etsako Central',
    'Etsako East',
    'Akoko-Edo',
    'Ovia North East',
    'Ovia South West',
    'Orhionmwon',
    'Uhunmwonde',
    'Igueben',
  ],
  'Ekiti': [
    'Ado-Ekiti',
    'Ikere',
    'Ijero',
    'Ikole',
    'Ise/Orun',
    'Emure',
    'Gbonyin',
    'Ido/Osi',
    'Irepodun/Ifelodun',
    'Moba',
    'Oye',
    'Efon',
  ],
  'Enugu': [
    'Enugu North',
    'Enugu South',
    'Enugu East',
    'Independence Layout',
    'New Haven',
    'GRA Enugu',
    'Nsukka',
    'Awgu',
    'Agwu',
    'Ezeagu',
    'Igbo Etiti',
    'Igbo Eze North',
    'Igbo Eze South',
    'Isi Uzo',
    'Nkanu East',
    'Nkanu West',
    'Oji River',
    'Udi',
    'Uzo Uwani',
  ],
  'Gombe': [
    'Gombe',
    'Akko',
    'Balanga',
    'Billiri',
    'Dukku',
    'Funakaye',
    'Kaltungo',
    'Kwami',
    'Nafada',
    'Shongom',
    'Yamaltu/Deba',
  ],
  'Imo': [
    'Owerri Municipal',
    'Owerri North',
    'Owerri West',
    'Orlu',
    'Okigwe',
    'Aboh Mbaise',
    'Ahiazu Mbaise',
    'Ezinihitte Mbaise',
    'Ideato North',
    'Ideato South',
    'Ihitte/Uboma',
    'Ikeduru',
    'Isiala Mbano',
    'Mbaitoli',
    'Ngor Okpala',
    'Njaba',
    'Nkwerre',
    'Oguta',
    'Ohaji/Egbema',
  ],
  'Jigawa': [
    'Dutse',
    'Hadejia',
    'Birnin Kudu',
    'Gumel',
    'Kazaure',
    'Babura',
    'Garki',
    'Jahun',
    'Kafin Hausa',
    'Ringim',
    'Taura',
  ],
  'Kaduna': [
    'Kaduna North',
    'Kaduna South',
    'Barnawa',
    'Malali',
    'Kakuri',
    'Zaria',
    'Kafanchan',
    'Chikun',
    'Giwa',
    'Igabi',
    'Ikara',
    'Jaba',
    'Jema\'a',
    'Kachia',
    'Kagarko',
    'Kajuru',
    'Kauru',
    'Kubau',
    'Kudan',
    'Lere',
    'Makarfi',
    'Sabon Gari',
    'Sanga',
    'Soba',
    'Zangon Kataf',
  ],
  'Kano': [
    'Kano Municipal',
    'Fagge',
    'Dala',
    'Gwale',
    'Tarauni',
    'Nassarawa',
    'Kumbotso',
    'Ungogo',
    'Bichi',
    'Dawakin Kudu',
    'Dawakin Tofa',
    'Gezawa',
    'Karaye',
    'Rano',
    'Wudil',
  ],
  'Katsina': [
    'Katsina',
    'Daura',
    'Funtua',
    'Bakori',
    'Batagarawa',
    'Batsari',
    'Danja',
    'Dutsin Ma',
    'Jibia',
    'Kankia',
    'Malumfashi',
    'Mani',
    'Safana',
  ],
  'Kebbi': [
    'Birnin Kebbi',
    'Argungu',
    'Yauri',
    'Zuru',
    'Aleiro',
    'Bagudo',
    'Dandi',
    'Gwandu',
    'Jega',
    'Maiyama',
    'Suru',
  ],
  'Kogi': [
    'Lokoja',
    'Okene',
    'Idah',
    'Kabba/Bunu',
    'Ankpa',
    'Ajaokuta',
    'Dekina',
    'Ibaji',
    'Igalamela Odolu',
    'Ijumu',
    'Kogi (K.K.)',
    'Mopa Muro',
    'Ofu',
    'Ogori/Magongo',
    'Okehi',
    'Olamaboro',
    'Omala',
    'Yagba East',
    'Yagba West',
  ],
  'Kwara': [
    'Ilorin South',
    'Ilorin West',
    'Ilorin East',
    'Offa',
    'Omu-Aran (Irepodun)',
    'Asa',
    'Baruten',
    'Edu',
    'Ekiti',
    'Ifelodun',
    'Isin',
    'Kaiama',
    'Moro',
    'Oke Ero',
    'Oyun',
    'Pategi',
  ],
  'Lagos': [
    'Ikeja',
    'Victoria Island',
    'Lekki Phase 1',
    'Lekki Phase 2 / Chevron',
    'Ikoyi',
    'Banana Island',
    'Ajah / Sangotedo',
    'Surulere',
    'Yaba',
    'Maryland',
    'Gbagada',
    'Magodo',
    'Ogudu',
    'Omole Phase 1 & 2',
    'Festac Town',
    'Apapa',
    'Oshodi-Isolo',
    'Agege',
    'Alimosho (Egbeda/Idimu/Ipaja)',
    'Ikorodu',
    'Epe',
    'Badagry',
    'Amuwo-Odofin',
    'Ifako-Ijaiye',
    'Kosofe',
    'Lagos Island',
    'Lagos Mainland',
    'Mushin',
    'Ojo',
    'Somolu',
  ],
  'Nasarawa': [
    'Lafia',
    'Keffi',
    'Akwanga',
    'Karu',
    'Mararaba',
    'Doma',
    'Keana',
    'Kokona',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Toto',
    'Wamba',
  ],
  'Niger': [
    'Minna (Chanchaga)',
    'Suleja',
    'Bida',
    'Kontagora',
    'Agaie',
    'Agwara',
    'Borgu',
    'Bosso',
    'Edati',
    'Gbako',
    'Gurara',
    'Katcha',
    'Lapai',
    'Lavun',
    'Magama',
    'Mariga',
    'Mokwa',
    'Moya',
    'Paikoro',
    'Rafi',
    'Rijau',
    'Shiroro',
    'Tafa',
    'Wushishi',
  ],
  'Ogun': [
    'Abeokuta South',
    'Abeokuta North',
    'Ikeja Border (Arepo/Berger)',
    'Mowe / Ibafo',
    'Sagamu',
    'Ijebu Ode',
    'Ota (Ado-Odo/Ota)',
    'Ewekoro',
    'Ifo',
    'Ijebu East',
    'Ijebu North',
    'Ijebu North East',
    'Ikenne',
    'Imeko Afon',
    'Ipokia',
    'Obafemi Owode',
    'Odeda',
    'Ogun Waterside',
    'Remo North',
    'Yewa North',
    'Yewa South',
  ],
  'Ondo': [
    'Akure South',
    'Akure North',
    'Ondo West',
    'Ondo East',
    'Owo',
    'Ikare Akoko',
    'Idanre',
    'Ifedore',
    'Ile Oluji/Okeigbo',
    'Ilaje',
    'Okitipupa',
    'Irele',
    'Odigbo',
    'Ose',
  ],
  'Osun': [
    'Osogbo',
    'Ile-Ife (Ife Central)',
    'Ife East',
    'Ife North',
    'Ife South',
    'Ede North',
    'Ede South',
    'Ilesa East',
    'Ilesa West',
    'Ikirun (Ifelodun)',
    'Ila',
    'Iwo',
    'Ayedaade',
    'Ayedire',
    'Boluwaduro',
    'Boripe',
    'Egbedore',
    'Ejigbo',
    'Isokan',
    'Obokun',
    'Odo Otin',
    'Ola Oluwa',
    'Olorunda',
    'Oriade',
    'Orolu',
  ],
  'Oyo': [
    'Ibadan North (Bodija/Agodi)',
    'Ibadan North East',
    'Ibadan North West (Dugbe/Onireke)',
    'Ibadan South East',
    'Ibadan South West (Ring Road/Oluyole)',
    'Oyo East',
    'Oyo West',
    'Ogbomosho North',
    'Ogbomosho South',
    'Iseyin',
    'Saki West',
    'Saki East',
    'Egbeda',
    'Ido',
    'Lagelu',
    'Oluyole',
    'Ona Ara',
    'Afijio',
    'Akinyele',
    'Atiba',
    'Atisbo',
    'Ibarapa Central',
    'Ibarapa East',
    'Ibarapa North',
    'Irepo',
    'Itesiwaju',
    'Iwajowa',
    'Kajola',
    'Ogo Oluwa',
    'Olorunsogo',
    'Orelope',
    'Ori Ire',
    'Surulere',
  ],
  'Plateau': [
    'Jos North',
    'Jos South',
    'Jos East',
    'Bukuru',
    'Barkin Ladi',
    'Bassa',
    'Bokkos',
    'Kanam',
    'Kanke',
    'Langtang North',
    'Langtang South',
    'Mangu',
    'Mikang',
    'Pankshin',
    'Qua\'an Pan',
    'Riyom',
    'Shendam',
    'Wase',
  ],
  'Rivers': [
    'Port Harcourt (GRA/Old GRA/D-Line)',
    'Obio/Akpor (Rumuokoro/Woji/Rumuola)',
    'Eleme',
    'Oyigbo',
    'Ikwerre',
    'Bonny Island',
    'Degema',
    'Ahoada East',
    'Ahoada West',
    'Akuku-Toru',
    'Andoni',
    'Asari-Toru',
    'Emohua',
    'Etche',
    'Gokana',
    'Khana',
    'Ogba/Egbema/Ndoni',
    'Ogu/Bolo',
    'Okrika',
    'Omuma',
    'Opobo/Nkoro',
    'Tai',
  ],
  'Sokoto': [
    'Sokoto North',
    'Sokoto South',
    'Bodinga',
    'Dange Shuni',
    'Gada',
    'Goronyo',
    'Gudu',
    'Gwadabawa',
    'Illela',
    'Isa',
    'Kebbe',
    'Kware',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Silame',
    'Tambuwal',
    'Tangaza',
    'Tureta',
    'Wamako',
    'Wurno',
    'Yabo',
  ],
  'Taraba': [
    'Jalingo',
    'Wukari',
    'Bali',
    'Donga',
    'Gashaka',
    'Gassol',
    'Ibi',
    'Karim Lamido',
    'Kurmi',
    'Lau',
    'Sardauna',
    'Takum',
    'Ussa',
    'Yorro',
    'Zing',
  ],
  'Yobe': [
    'Damaturu',
    'Potiskum',
    'Gashua (Bade)',
    'Bursari',
    'Geidam',
    'Gujba',
    'Gulani',
    'Fika',
    'Fune',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Nguru',
    'Tarmuwa',
    'Yunusari',
    'Yusufari',
  ],
  'Zamfara': [
    'Gusau',
    'Kaura Namoda',
    'Talata Mafara',
    'Anka',
    'Bakura',
    'Birnin Magaji/Kiyaw',
    'Bukkuyum',
    'Bungudu',
    'Gummi',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Tsafe',
    'Zurmi',
  ],
};

export const ALL_STATES = Object.keys(NIGERIA_STATES).sort();
